CXX = cl.exe
CFLAGS = -nologo -O2 -EHsc -I. -D __WIN32__ -D _CRT_SECURE_NO_DEPRECATE -I../public/
TARGET = windows

all: $(TARGET)\test_basic.exe $(TARGET)\test_thread.exe

$(TARGET)\test_basic.exe: test_basic\main.cpp
	$(CXX) $(CFLAGS) test_basic\main.cpp -Fe$(TARGET)\test_basic.exe

$(TARGET)\test_thread.exe: test_thread\main.cpp
	$(CXX) $(CFLAGS) test_thread\main.cpp -Fe$(TARGET)\test_thread.exe

clean:
	-erase /Q *.obj $(TARGET)\.
