// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 10003_S2CRegisterRsp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "10003_S2CRegisterRsp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* S2CRegisterRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S2CRegisterRsp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_10003_5fS2CRegisterRsp_2eproto() {
  protobuf_AddDesc_10003_5fS2CRegisterRsp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "10003_S2CRegisterRsp.proto");
  GOOGLE_CHECK(file != NULL);
  S2CRegisterRsp_descriptor_ = file->message_type(0);
  static const int S2CRegisterRsp_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CRegisterRsp, register_result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CRegisterRsp, failed_reason_),
  };
  S2CRegisterRsp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      S2CRegisterRsp_descriptor_,
      S2CRegisterRsp::default_instance_,
      S2CRegisterRsp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CRegisterRsp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CRegisterRsp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(S2CRegisterRsp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_10003_5fS2CRegisterRsp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    S2CRegisterRsp_descriptor_, &S2CRegisterRsp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_10003_5fS2CRegisterRsp_2eproto() {
  delete S2CRegisterRsp::default_instance_;
  delete S2CRegisterRsp_reflection_;
}

void protobuf_AddDesc_10003_5fS2CRegisterRsp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\03210003_S2CRegisterRsp.proto\022\010Protocol\"@"
    "\n\016S2CRegisterRsp\022\027\n\017register_result\030\001 \002("
    "\010\022\025\n\rfailed_reason\030\002 \001(\014", 104);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "10003_S2CRegisterRsp.proto", &protobuf_RegisterTypes);
  S2CRegisterRsp::default_instance_ = new S2CRegisterRsp();
  S2CRegisterRsp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_10003_5fS2CRegisterRsp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_10003_5fS2CRegisterRsp_2eproto {
  StaticDescriptorInitializer_10003_5fS2CRegisterRsp_2eproto() {
    protobuf_AddDesc_10003_5fS2CRegisterRsp_2eproto();
  }
} static_descriptor_initializer_10003_5fS2CRegisterRsp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int S2CRegisterRsp::kRegisterResultFieldNumber;
const int S2CRegisterRsp::kFailedReasonFieldNumber;
#endif  // !_MSC_VER

S2CRegisterRsp::S2CRegisterRsp()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void S2CRegisterRsp::InitAsDefaultInstance() {
}

S2CRegisterRsp::S2CRegisterRsp(const S2CRegisterRsp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void S2CRegisterRsp::SharedCtor() {
  _cached_size_ = 0;
  register_result_ = false;
  failed_reason_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S2CRegisterRsp::~S2CRegisterRsp() {
  SharedDtor();
}

void S2CRegisterRsp::SharedDtor() {
  if (failed_reason_ != &::google::protobuf::internal::kEmptyString) {
    delete failed_reason_;
  }
  if (this != default_instance_) {
  }
}

void S2CRegisterRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2CRegisterRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S2CRegisterRsp_descriptor_;
}

const S2CRegisterRsp& S2CRegisterRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_10003_5fS2CRegisterRsp_2eproto();
  return *default_instance_;
}

S2CRegisterRsp* S2CRegisterRsp::default_instance_ = NULL;

S2CRegisterRsp* S2CRegisterRsp::New() const {
  return new S2CRegisterRsp;
}

void S2CRegisterRsp::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    register_result_ = false;
    if (has_failed_reason()) {
      if (failed_reason_ != &::google::protobuf::internal::kEmptyString) {
        failed_reason_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool S2CRegisterRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool register_result = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &register_result_)));
          set_has_register_result();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_failed_reason;
        break;
      }

      // optional bytes failed_reason = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_failed_reason:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_failed_reason()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void S2CRegisterRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bool register_result = 1;
  if (has_register_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->register_result(), output);
  }

  // optional bytes failed_reason = 2;
  if (has_failed_reason()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->failed_reason(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* S2CRegisterRsp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bool register_result = 1;
  if (has_register_result()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->register_result(), target);
  }

  // optional bytes failed_reason = 2;
  if (has_failed_reason()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->failed_reason(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int S2CRegisterRsp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bool register_result = 1;
    if (has_register_result()) {
      total_size += 1 + 1;
    }

    // optional bytes failed_reason = 2;
    if (has_failed_reason()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->failed_reason());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2CRegisterRsp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const S2CRegisterRsp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const S2CRegisterRsp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S2CRegisterRsp::MergeFrom(const S2CRegisterRsp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_register_result()) {
      set_register_result(from.register_result());
    }
    if (from.has_failed_reason()) {
      set_failed_reason(from.failed_reason());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void S2CRegisterRsp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2CRegisterRsp::CopyFrom(const S2CRegisterRsp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2CRegisterRsp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void S2CRegisterRsp::Swap(S2CRegisterRsp* other) {
  if (other != this) {
    std::swap(register_result_, other->register_result_);
    std::swap(failed_reason_, other->failed_reason_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata S2CRegisterRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S2CRegisterRsp_descriptor_;
  metadata.reflection = S2CRegisterRsp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
