// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 15001_S2CGetPlayerProfileRsp.proto

#ifndef PROTOBUF_15001_5fS2CGetPlayerProfileRsp_2eproto__INCLUDED
#define PROTOBUF_15001_5fS2CGetPlayerProfileRsp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_15001_5fS2CGetPlayerProfileRsp_2eproto();
void protobuf_AssignDesc_15001_5fS2CGetPlayerProfileRsp_2eproto();
void protobuf_ShutdownFile_15001_5fS2CGetPlayerProfileRsp_2eproto();

class S2CGetPlayerProfileRsp;

// ===================================================================

class S2CGetPlayerProfileRsp : public ::google::protobuf::Message {
 public:
  S2CGetPlayerProfileRsp();
  virtual ~S2CGetPlayerProfileRsp();

  S2CGetPlayerProfileRsp(const S2CGetPlayerProfileRsp& from);

  inline S2CGetPlayerProfileRsp& operator=(const S2CGetPlayerProfileRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CGetPlayerProfileRsp& default_instance();

  void Swap(S2CGetPlayerProfileRsp* other);

  // implements Message ----------------------------------------------

  S2CGetPlayerProfileRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CGetPlayerProfileRsp& from);
  void MergeFrom(const S2CGetPlayerProfileRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 guid = 1;
  inline bool has_guid() const;
  inline void clear_guid();
  static const int kGuidFieldNumber = 1;
  inline ::google::protobuf::uint64 guid() const;
  inline void set_guid(::google::protobuf::uint64 value);

  // required int32 gender = 2;
  inline bool has_gender() const;
  inline void clear_gender();
  static const int kGenderFieldNumber = 2;
  inline ::google::protobuf::int32 gender() const;
  inline void set_gender(::google::protobuf::int32 value);

  // required bytes nickname = 3;
  inline bool has_nickname() const;
  inline void clear_nickname();
  static const int kNicknameFieldNumber = 3;
  inline const ::std::string& nickname() const;
  inline void set_nickname(const ::std::string& value);
  inline void set_nickname(const char* value);
  inline void set_nickname(const void* value, size_t size);
  inline ::std::string* mutable_nickname();
  inline ::std::string* release_nickname();
  inline void set_allocated_nickname(::std::string* nickname);

  // required int64 last_login = 4;
  inline bool has_last_login() const;
  inline void clear_last_login();
  static const int kLastLoginFieldNumber = 4;
  inline ::google::protobuf::int64 last_login() const;
  inline void set_last_login(::google::protobuf::int64 value);

  // required uint64 guild_id = 5;
  inline bool has_guild_id() const;
  inline void clear_guild_id();
  static const int kGuildIdFieldNumber = 5;
  inline ::google::protobuf::uint64 guild_id() const;
  inline void set_guild_id(::google::protobuf::uint64 value);

  // required bytes guild_name = 6;
  inline bool has_guild_name() const;
  inline void clear_guild_name();
  static const int kGuildNameFieldNumber = 6;
  inline const ::std::string& guild_name() const;
  inline void set_guild_name(const ::std::string& value);
  inline void set_guild_name(const char* value);
  inline void set_guild_name(const void* value, size_t size);
  inline ::std::string* mutable_guild_name();
  inline ::std::string* release_guild_name();
  inline void set_allocated_guild_name(::std::string* guild_name);

  // required uint32 gold = 7;
  inline bool has_gold() const;
  inline void clear_gold();
  static const int kGoldFieldNumber = 7;
  inline ::google::protobuf::uint32 gold() const;
  inline void set_gold(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Protocol.S2CGetPlayerProfileRsp)
 private:
  inline void set_has_guid();
  inline void clear_has_guid();
  inline void set_has_gender();
  inline void clear_has_gender();
  inline void set_has_nickname();
  inline void clear_has_nickname();
  inline void set_has_last_login();
  inline void clear_has_last_login();
  inline void set_has_guild_id();
  inline void clear_has_guild_id();
  inline void set_has_guild_name();
  inline void clear_has_guild_name();
  inline void set_has_gold();
  inline void clear_has_gold();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 guid_;
  ::std::string* nickname_;
  ::google::protobuf::int64 last_login_;
  ::google::protobuf::int32 gender_;
  ::google::protobuf::uint32 gold_;
  ::google::protobuf::uint64 guild_id_;
  ::std::string* guild_name_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_15001_5fS2CGetPlayerProfileRsp_2eproto();
  friend void protobuf_AssignDesc_15001_5fS2CGetPlayerProfileRsp_2eproto();
  friend void protobuf_ShutdownFile_15001_5fS2CGetPlayerProfileRsp_2eproto();

  void InitAsDefaultInstance();
  static S2CGetPlayerProfileRsp* default_instance_;
};
// ===================================================================


// ===================================================================

// S2CGetPlayerProfileRsp

// required uint64 guid = 1;
inline bool S2CGetPlayerProfileRsp::has_guid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CGetPlayerProfileRsp::set_has_guid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CGetPlayerProfileRsp::clear_has_guid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CGetPlayerProfileRsp::clear_guid() {
  guid_ = GOOGLE_ULONGLONG(0);
  clear_has_guid();
}
inline ::google::protobuf::uint64 S2CGetPlayerProfileRsp::guid() const {
  return guid_;
}
inline void S2CGetPlayerProfileRsp::set_guid(::google::protobuf::uint64 value) {
  set_has_guid();
  guid_ = value;
}

// required int32 gender = 2;
inline bool S2CGetPlayerProfileRsp::has_gender() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CGetPlayerProfileRsp::set_has_gender() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CGetPlayerProfileRsp::clear_has_gender() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CGetPlayerProfileRsp::clear_gender() {
  gender_ = 0;
  clear_has_gender();
}
inline ::google::protobuf::int32 S2CGetPlayerProfileRsp::gender() const {
  return gender_;
}
inline void S2CGetPlayerProfileRsp::set_gender(::google::protobuf::int32 value) {
  set_has_gender();
  gender_ = value;
}

// required bytes nickname = 3;
inline bool S2CGetPlayerProfileRsp::has_nickname() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void S2CGetPlayerProfileRsp::set_has_nickname() {
  _has_bits_[0] |= 0x00000004u;
}
inline void S2CGetPlayerProfileRsp::clear_has_nickname() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void S2CGetPlayerProfileRsp::clear_nickname() {
  if (nickname_ != &::google::protobuf::internal::kEmptyString) {
    nickname_->clear();
  }
  clear_has_nickname();
}
inline const ::std::string& S2CGetPlayerProfileRsp::nickname() const {
  return *nickname_;
}
inline void S2CGetPlayerProfileRsp::set_nickname(const ::std::string& value) {
  set_has_nickname();
  if (nickname_ == &::google::protobuf::internal::kEmptyString) {
    nickname_ = new ::std::string;
  }
  nickname_->assign(value);
}
inline void S2CGetPlayerProfileRsp::set_nickname(const char* value) {
  set_has_nickname();
  if (nickname_ == &::google::protobuf::internal::kEmptyString) {
    nickname_ = new ::std::string;
  }
  nickname_->assign(value);
}
inline void S2CGetPlayerProfileRsp::set_nickname(const void* value, size_t size) {
  set_has_nickname();
  if (nickname_ == &::google::protobuf::internal::kEmptyString) {
    nickname_ = new ::std::string;
  }
  nickname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* S2CGetPlayerProfileRsp::mutable_nickname() {
  set_has_nickname();
  if (nickname_ == &::google::protobuf::internal::kEmptyString) {
    nickname_ = new ::std::string;
  }
  return nickname_;
}
inline ::std::string* S2CGetPlayerProfileRsp::release_nickname() {
  clear_has_nickname();
  if (nickname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = nickname_;
    nickname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void S2CGetPlayerProfileRsp::set_allocated_nickname(::std::string* nickname) {
  if (nickname_ != &::google::protobuf::internal::kEmptyString) {
    delete nickname_;
  }
  if (nickname) {
    set_has_nickname();
    nickname_ = nickname;
  } else {
    clear_has_nickname();
    nickname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int64 last_login = 4;
inline bool S2CGetPlayerProfileRsp::has_last_login() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void S2CGetPlayerProfileRsp::set_has_last_login() {
  _has_bits_[0] |= 0x00000008u;
}
inline void S2CGetPlayerProfileRsp::clear_has_last_login() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void S2CGetPlayerProfileRsp::clear_last_login() {
  last_login_ = GOOGLE_LONGLONG(0);
  clear_has_last_login();
}
inline ::google::protobuf::int64 S2CGetPlayerProfileRsp::last_login() const {
  return last_login_;
}
inline void S2CGetPlayerProfileRsp::set_last_login(::google::protobuf::int64 value) {
  set_has_last_login();
  last_login_ = value;
}

// required uint64 guild_id = 5;
inline bool S2CGetPlayerProfileRsp::has_guild_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void S2CGetPlayerProfileRsp::set_has_guild_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void S2CGetPlayerProfileRsp::clear_has_guild_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void S2CGetPlayerProfileRsp::clear_guild_id() {
  guild_id_ = GOOGLE_ULONGLONG(0);
  clear_has_guild_id();
}
inline ::google::protobuf::uint64 S2CGetPlayerProfileRsp::guild_id() const {
  return guild_id_;
}
inline void S2CGetPlayerProfileRsp::set_guild_id(::google::protobuf::uint64 value) {
  set_has_guild_id();
  guild_id_ = value;
}

// required bytes guild_name = 6;
inline bool S2CGetPlayerProfileRsp::has_guild_name() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void S2CGetPlayerProfileRsp::set_has_guild_name() {
  _has_bits_[0] |= 0x00000020u;
}
inline void S2CGetPlayerProfileRsp::clear_has_guild_name() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void S2CGetPlayerProfileRsp::clear_guild_name() {
  if (guild_name_ != &::google::protobuf::internal::kEmptyString) {
    guild_name_->clear();
  }
  clear_has_guild_name();
}
inline const ::std::string& S2CGetPlayerProfileRsp::guild_name() const {
  return *guild_name_;
}
inline void S2CGetPlayerProfileRsp::set_guild_name(const ::std::string& value) {
  set_has_guild_name();
  if (guild_name_ == &::google::protobuf::internal::kEmptyString) {
    guild_name_ = new ::std::string;
  }
  guild_name_->assign(value);
}
inline void S2CGetPlayerProfileRsp::set_guild_name(const char* value) {
  set_has_guild_name();
  if (guild_name_ == &::google::protobuf::internal::kEmptyString) {
    guild_name_ = new ::std::string;
  }
  guild_name_->assign(value);
}
inline void S2CGetPlayerProfileRsp::set_guild_name(const void* value, size_t size) {
  set_has_guild_name();
  if (guild_name_ == &::google::protobuf::internal::kEmptyString) {
    guild_name_ = new ::std::string;
  }
  guild_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* S2CGetPlayerProfileRsp::mutable_guild_name() {
  set_has_guild_name();
  if (guild_name_ == &::google::protobuf::internal::kEmptyString) {
    guild_name_ = new ::std::string;
  }
  return guild_name_;
}
inline ::std::string* S2CGetPlayerProfileRsp::release_guild_name() {
  clear_has_guild_name();
  if (guild_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = guild_name_;
    guild_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void S2CGetPlayerProfileRsp::set_allocated_guild_name(::std::string* guild_name) {
  if (guild_name_ != &::google::protobuf::internal::kEmptyString) {
    delete guild_name_;
  }
  if (guild_name) {
    set_has_guild_name();
    guild_name_ = guild_name;
  } else {
    clear_has_guild_name();
    guild_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required uint32 gold = 7;
inline bool S2CGetPlayerProfileRsp::has_gold() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void S2CGetPlayerProfileRsp::set_has_gold() {
  _has_bits_[0] |= 0x00000040u;
}
inline void S2CGetPlayerProfileRsp::clear_has_gold() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void S2CGetPlayerProfileRsp::clear_gold() {
  gold_ = 0u;
  clear_has_gold();
}
inline ::google::protobuf::uint32 S2CGetPlayerProfileRsp::gold() const {
  return gold_;
}
inline void S2CGetPlayerProfileRsp::set_gold(::google::protobuf::uint32 value) {
  set_has_gold();
  gold_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_15001_5fS2CGetPlayerProfileRsp_2eproto__INCLUDED
