// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 21008_S2CRoomInfoChangeNotify.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "21008_S2CRoomInfoChangeNotify.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* S2CSRoomInfoChangeNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S2CSRoomInfoChangeNotify_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_21008_5fS2CRoomInfoChangeNotify_2eproto() {
  protobuf_AddDesc_21008_5fS2CRoomInfoChangeNotify_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "21008_S2CRoomInfoChangeNotify.proto");
  GOOGLE_CHECK(file != NULL);
  S2CSRoomInfoChangeNotify_descriptor_ = file->message_type(0);
  static const int S2CSRoomInfoChangeNotify_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CSRoomInfoChangeNotify, room_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CSRoomInfoChangeNotify, room_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CSRoomInfoChangeNotify, player_count_),
  };
  S2CSRoomInfoChangeNotify_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      S2CSRoomInfoChangeNotify_descriptor_,
      S2CSRoomInfoChangeNotify::default_instance_,
      S2CSRoomInfoChangeNotify_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CSRoomInfoChangeNotify, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CSRoomInfoChangeNotify, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(S2CSRoomInfoChangeNotify));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_21008_5fS2CRoomInfoChangeNotify_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    S2CSRoomInfoChangeNotify_descriptor_, &S2CSRoomInfoChangeNotify::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_21008_5fS2CRoomInfoChangeNotify_2eproto() {
  delete S2CSRoomInfoChangeNotify::default_instance_;
  delete S2CSRoomInfoChangeNotify_reflection_;
}

void protobuf_AddDesc_21008_5fS2CRoomInfoChangeNotify_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n#21008_S2CRoomInfoChangeNotify.proto\022\010P"
    "rotocol\"T\n\030S2CSRoomInfoChangeNotify\022\017\n\007r"
    "oom_id\030\001 \002(\r\022\021\n\troom_name\030\002 \001(\t\022\024\n\014playe"
    "r_count\030\003 \001(\r", 133);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "21008_S2CRoomInfoChangeNotify.proto", &protobuf_RegisterTypes);
  S2CSRoomInfoChangeNotify::default_instance_ = new S2CSRoomInfoChangeNotify();
  S2CSRoomInfoChangeNotify::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_21008_5fS2CRoomInfoChangeNotify_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_21008_5fS2CRoomInfoChangeNotify_2eproto {
  StaticDescriptorInitializer_21008_5fS2CRoomInfoChangeNotify_2eproto() {
    protobuf_AddDesc_21008_5fS2CRoomInfoChangeNotify_2eproto();
  }
} static_descriptor_initializer_21008_5fS2CRoomInfoChangeNotify_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int S2CSRoomInfoChangeNotify::kRoomIdFieldNumber;
const int S2CSRoomInfoChangeNotify::kRoomNameFieldNumber;
const int S2CSRoomInfoChangeNotify::kPlayerCountFieldNumber;
#endif  // !_MSC_VER

S2CSRoomInfoChangeNotify::S2CSRoomInfoChangeNotify()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void S2CSRoomInfoChangeNotify::InitAsDefaultInstance() {
}

S2CSRoomInfoChangeNotify::S2CSRoomInfoChangeNotify(const S2CSRoomInfoChangeNotify& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void S2CSRoomInfoChangeNotify::SharedCtor() {
  _cached_size_ = 0;
  room_id_ = 0u;
  room_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  player_count_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S2CSRoomInfoChangeNotify::~S2CSRoomInfoChangeNotify() {
  SharedDtor();
}

void S2CSRoomInfoChangeNotify::SharedDtor() {
  if (room_name_ != &::google::protobuf::internal::kEmptyString) {
    delete room_name_;
  }
  if (this != default_instance_) {
  }
}

void S2CSRoomInfoChangeNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2CSRoomInfoChangeNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S2CSRoomInfoChangeNotify_descriptor_;
}

const S2CSRoomInfoChangeNotify& S2CSRoomInfoChangeNotify::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_21008_5fS2CRoomInfoChangeNotify_2eproto();
  return *default_instance_;
}

S2CSRoomInfoChangeNotify* S2CSRoomInfoChangeNotify::default_instance_ = NULL;

S2CSRoomInfoChangeNotify* S2CSRoomInfoChangeNotify::New() const {
  return new S2CSRoomInfoChangeNotify;
}

void S2CSRoomInfoChangeNotify::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    room_id_ = 0u;
    if (has_room_name()) {
      if (room_name_ != &::google::protobuf::internal::kEmptyString) {
        room_name_->clear();
      }
    }
    player_count_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool S2CSRoomInfoChangeNotify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 room_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &room_id_)));
          set_has_room_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_room_name;
        break;
      }

      // optional string room_name = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_room_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_room_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->room_name().data(), this->room_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_player_count;
        break;
      }

      // optional uint32 player_count = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_player_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &player_count_)));
          set_has_player_count();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void S2CSRoomInfoChangeNotify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 room_id = 1;
  if (has_room_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->room_id(), output);
  }

  // optional string room_name = 2;
  if (has_room_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->room_name().data(), this->room_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->room_name(), output);
  }

  // optional uint32 player_count = 3;
  if (has_player_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->player_count(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* S2CSRoomInfoChangeNotify::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 room_id = 1;
  if (has_room_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->room_id(), target);
  }

  // optional string room_name = 2;
  if (has_room_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->room_name().data(), this->room_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->room_name(), target);
  }

  // optional uint32 player_count = 3;
  if (has_player_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->player_count(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int S2CSRoomInfoChangeNotify::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 room_id = 1;
    if (has_room_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->room_id());
    }

    // optional string room_name = 2;
    if (has_room_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->room_name());
    }

    // optional uint32 player_count = 3;
    if (has_player_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->player_count());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2CSRoomInfoChangeNotify::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const S2CSRoomInfoChangeNotify* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const S2CSRoomInfoChangeNotify*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S2CSRoomInfoChangeNotify::MergeFrom(const S2CSRoomInfoChangeNotify& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_room_id()) {
      set_room_id(from.room_id());
    }
    if (from.has_room_name()) {
      set_room_name(from.room_name());
    }
    if (from.has_player_count()) {
      set_player_count(from.player_count());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void S2CSRoomInfoChangeNotify::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2CSRoomInfoChangeNotify::CopyFrom(const S2CSRoomInfoChangeNotify& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2CSRoomInfoChangeNotify::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void S2CSRoomInfoChangeNotify::Swap(S2CSRoomInfoChangeNotify* other) {
  if (other != this) {
    std::swap(room_id_, other->room_id_);
    std::swap(room_name_, other->room_name_);
    std::swap(player_count_, other->player_count_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata S2CSRoomInfoChangeNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S2CSRoomInfoChangeNotify_descriptor_;
  metadata.reflection = S2CSRoomInfoChangeNotify_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
