// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 21002_S2CRoomCreateRsp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "21002_S2CRoomCreateRsp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* S2CRoomCreateRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S2CRoomCreateRsp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_21002_5fS2CRoomCreateRsp_2eproto() {
  protobuf_AddDesc_21002_5fS2CRoomCreateRsp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "21002_S2CRoomCreateRsp.proto");
  GOOGLE_CHECK(file != NULL);
  S2CRoomCreateRsp_descriptor_ = file->message_type(0);
  static const int S2CRoomCreateRsp_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CRoomCreateRsp, room_create_result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CRoomCreateRsp, room_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CRoomCreateRsp, failed_reason_),
  };
  S2CRoomCreateRsp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      S2CRoomCreateRsp_descriptor_,
      S2CRoomCreateRsp::default_instance_,
      S2CRoomCreateRsp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CRoomCreateRsp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CRoomCreateRsp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(S2CRoomCreateRsp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_21002_5fS2CRoomCreateRsp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    S2CRoomCreateRsp_descriptor_, &S2CRoomCreateRsp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_21002_5fS2CRoomCreateRsp_2eproto() {
  delete S2CRoomCreateRsp::default_instance_;
  delete S2CRoomCreateRsp_reflection_;
}

void protobuf_AddDesc_21002_5fS2CRoomCreateRsp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\03421002_S2CRoomCreateRsp.proto\022\010Protocol"
    "\"V\n\020S2CRoomCreateRsp\022\032\n\022room_create_resu"
    "lt\030\001 \002(\010\022\017\n\007room_id\030\002 \001(\r\022\025\n\rfailed_reas"
    "on\030\003 \001(\014", 128);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "21002_S2CRoomCreateRsp.proto", &protobuf_RegisterTypes);
  S2CRoomCreateRsp::default_instance_ = new S2CRoomCreateRsp();
  S2CRoomCreateRsp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_21002_5fS2CRoomCreateRsp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_21002_5fS2CRoomCreateRsp_2eproto {
  StaticDescriptorInitializer_21002_5fS2CRoomCreateRsp_2eproto() {
    protobuf_AddDesc_21002_5fS2CRoomCreateRsp_2eproto();
  }
} static_descriptor_initializer_21002_5fS2CRoomCreateRsp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int S2CRoomCreateRsp::kRoomCreateResultFieldNumber;
const int S2CRoomCreateRsp::kRoomIdFieldNumber;
const int S2CRoomCreateRsp::kFailedReasonFieldNumber;
#endif  // !_MSC_VER

S2CRoomCreateRsp::S2CRoomCreateRsp()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void S2CRoomCreateRsp::InitAsDefaultInstance() {
}

S2CRoomCreateRsp::S2CRoomCreateRsp(const S2CRoomCreateRsp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void S2CRoomCreateRsp::SharedCtor() {
  _cached_size_ = 0;
  room_create_result_ = false;
  room_id_ = 0u;
  failed_reason_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S2CRoomCreateRsp::~S2CRoomCreateRsp() {
  SharedDtor();
}

void S2CRoomCreateRsp::SharedDtor() {
  if (failed_reason_ != &::google::protobuf::internal::kEmptyString) {
    delete failed_reason_;
  }
  if (this != default_instance_) {
  }
}

void S2CRoomCreateRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2CRoomCreateRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S2CRoomCreateRsp_descriptor_;
}

const S2CRoomCreateRsp& S2CRoomCreateRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_21002_5fS2CRoomCreateRsp_2eproto();
  return *default_instance_;
}

S2CRoomCreateRsp* S2CRoomCreateRsp::default_instance_ = NULL;

S2CRoomCreateRsp* S2CRoomCreateRsp::New() const {
  return new S2CRoomCreateRsp;
}

void S2CRoomCreateRsp::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    room_create_result_ = false;
    room_id_ = 0u;
    if (has_failed_reason()) {
      if (failed_reason_ != &::google::protobuf::internal::kEmptyString) {
        failed_reason_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool S2CRoomCreateRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool room_create_result = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &room_create_result_)));
          set_has_room_create_result();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_room_id;
        break;
      }

      // optional uint32 room_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_room_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &room_id_)));
          set_has_room_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_failed_reason;
        break;
      }

      // optional bytes failed_reason = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_failed_reason:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_failed_reason()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void S2CRoomCreateRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bool room_create_result = 1;
  if (has_room_create_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->room_create_result(), output);
  }

  // optional uint32 room_id = 2;
  if (has_room_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->room_id(), output);
  }

  // optional bytes failed_reason = 3;
  if (has_failed_reason()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      3, this->failed_reason(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* S2CRoomCreateRsp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bool room_create_result = 1;
  if (has_room_create_result()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->room_create_result(), target);
  }

  // optional uint32 room_id = 2;
  if (has_room_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->room_id(), target);
  }

  // optional bytes failed_reason = 3;
  if (has_failed_reason()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->failed_reason(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int S2CRoomCreateRsp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bool room_create_result = 1;
    if (has_room_create_result()) {
      total_size += 1 + 1;
    }

    // optional uint32 room_id = 2;
    if (has_room_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->room_id());
    }

    // optional bytes failed_reason = 3;
    if (has_failed_reason()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->failed_reason());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2CRoomCreateRsp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const S2CRoomCreateRsp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const S2CRoomCreateRsp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S2CRoomCreateRsp::MergeFrom(const S2CRoomCreateRsp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_room_create_result()) {
      set_room_create_result(from.room_create_result());
    }
    if (from.has_room_id()) {
      set_room_id(from.room_id());
    }
    if (from.has_failed_reason()) {
      set_failed_reason(from.failed_reason());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void S2CRoomCreateRsp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2CRoomCreateRsp::CopyFrom(const S2CRoomCreateRsp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2CRoomCreateRsp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void S2CRoomCreateRsp::Swap(S2CRoomCreateRsp* other) {
  if (other != this) {
    std::swap(room_create_result_, other->room_create_result_);
    std::swap(room_id_, other->room_id_);
    std::swap(failed_reason_, other->failed_reason_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata S2CRoomCreateRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S2CRoomCreateRsp_descriptor_;
  metadata.reflection = S2CRoomCreateRsp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
