// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 21003_C2SGetRoomListReq.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "21003_C2SGetRoomListReq.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* C2SGetRoomListReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  C2SGetRoomListReq_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_21003_5fC2SGetRoomListReq_2eproto() {
  protobuf_AddDesc_21003_5fC2SGetRoomListReq_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "21003_C2SGetRoomListReq.proto");
  GOOGLE_CHECK(file != NULL);
  C2SGetRoomListReq_descriptor_ = file->message_type(0);
  static const int C2SGetRoomListReq_offsets_[1] = {
  };
  C2SGetRoomListReq_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      C2SGetRoomListReq_descriptor_,
      C2SGetRoomListReq::default_instance_,
      C2SGetRoomListReq_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2SGetRoomListReq, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2SGetRoomListReq, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(C2SGetRoomListReq));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_21003_5fC2SGetRoomListReq_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    C2SGetRoomListReq_descriptor_, &C2SGetRoomListReq::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_21003_5fC2SGetRoomListReq_2eproto() {
  delete C2SGetRoomListReq::default_instance_;
  delete C2SGetRoomListReq_reflection_;
}

void protobuf_AddDesc_21003_5fC2SGetRoomListReq_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\03521003_C2SGetRoomListReq.proto\022\010Protoco"
    "l\"\023\n\021C2SGetRoomListReq", 62);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "21003_C2SGetRoomListReq.proto", &protobuf_RegisterTypes);
  C2SGetRoomListReq::default_instance_ = new C2SGetRoomListReq();
  C2SGetRoomListReq::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_21003_5fC2SGetRoomListReq_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_21003_5fC2SGetRoomListReq_2eproto {
  StaticDescriptorInitializer_21003_5fC2SGetRoomListReq_2eproto() {
    protobuf_AddDesc_21003_5fC2SGetRoomListReq_2eproto();
  }
} static_descriptor_initializer_21003_5fC2SGetRoomListReq_2eproto_;

// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

C2SGetRoomListReq::C2SGetRoomListReq()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void C2SGetRoomListReq::InitAsDefaultInstance() {
}

C2SGetRoomListReq::C2SGetRoomListReq(const C2SGetRoomListReq& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void C2SGetRoomListReq::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

C2SGetRoomListReq::~C2SGetRoomListReq() {
  SharedDtor();
}

void C2SGetRoomListReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void C2SGetRoomListReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* C2SGetRoomListReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return C2SGetRoomListReq_descriptor_;
}

const C2SGetRoomListReq& C2SGetRoomListReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_21003_5fC2SGetRoomListReq_2eproto();
  return *default_instance_;
}

C2SGetRoomListReq* C2SGetRoomListReq::default_instance_ = NULL;

C2SGetRoomListReq* C2SGetRoomListReq::New() const {
  return new C2SGetRoomListReq;
}

void C2SGetRoomListReq::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool C2SGetRoomListReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void C2SGetRoomListReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* C2SGetRoomListReq::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int C2SGetRoomListReq::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void C2SGetRoomListReq::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const C2SGetRoomListReq* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const C2SGetRoomListReq*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void C2SGetRoomListReq::MergeFrom(const C2SGetRoomListReq& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void C2SGetRoomListReq::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2SGetRoomListReq::CopyFrom(const C2SGetRoomListReq& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2SGetRoomListReq::IsInitialized() const {

  return true;
}

void C2SGetRoomListReq::Swap(C2SGetRoomListReq* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata C2SGetRoomListReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = C2SGetRoomListReq_descriptor_;
  metadata.reflection = C2SGetRoomListReq_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
