// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 21004_S2CGetRoomListRsp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "21004_S2CGetRoomListRsp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* S2CGetRoomListRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S2CGetRoomListRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* S2CGetRoomListRsp_RoomInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S2CGetRoomListRsp_RoomInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_21004_5fS2CGetRoomListRsp_2eproto() {
  protobuf_AddDesc_21004_5fS2CGetRoomListRsp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "21004_S2CGetRoomListRsp.proto");
  GOOGLE_CHECK(file != NULL);
  S2CGetRoomListRsp_descriptor_ = file->message_type(0);
  static const int S2CGetRoomListRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CGetRoomListRsp, room_list_),
  };
  S2CGetRoomListRsp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      S2CGetRoomListRsp_descriptor_,
      S2CGetRoomListRsp::default_instance_,
      S2CGetRoomListRsp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CGetRoomListRsp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CGetRoomListRsp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(S2CGetRoomListRsp));
  S2CGetRoomListRsp_RoomInfo_descriptor_ = S2CGetRoomListRsp_descriptor_->nested_type(0);
  static const int S2CGetRoomListRsp_RoomInfo_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CGetRoomListRsp_RoomInfo, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CGetRoomListRsp_RoomInfo, room_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CGetRoomListRsp_RoomInfo, player_count_),
  };
  S2CGetRoomListRsp_RoomInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      S2CGetRoomListRsp_RoomInfo_descriptor_,
      S2CGetRoomListRsp_RoomInfo::default_instance_,
      S2CGetRoomListRsp_RoomInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CGetRoomListRsp_RoomInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CGetRoomListRsp_RoomInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(S2CGetRoomListRsp_RoomInfo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_21004_5fS2CGetRoomListRsp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    S2CGetRoomListRsp_descriptor_, &S2CGetRoomListRsp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    S2CGetRoomListRsp_RoomInfo_descriptor_, &S2CGetRoomListRsp_RoomInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_21004_5fS2CGetRoomListRsp_2eproto() {
  delete S2CGetRoomListRsp::default_instance_;
  delete S2CGetRoomListRsp_reflection_;
  delete S2CGetRoomListRsp_RoomInfo::default_instance_;
  delete S2CGetRoomListRsp_RoomInfo_reflection_;
}

void protobuf_AddDesc_21004_5fS2CGetRoomListRsp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\03521004_S2CGetRoomListRsp.proto\022\010Protoco"
    "l\"\215\001\n\021S2CGetRoomListRsp\0227\n\troom_list\030\001 \003"
    "(\0132$.Protocol.S2CGetRoomListRsp.RoomInfo"
    "\032\?\n\010RoomInfo\022\n\n\002id\030\001 \002(\r\022\021\n\troom_name\030\002 "
    "\002(\t\022\024\n\014player_count\030\003 \002(\r", 185);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "21004_S2CGetRoomListRsp.proto", &protobuf_RegisterTypes);
  S2CGetRoomListRsp::default_instance_ = new S2CGetRoomListRsp();
  S2CGetRoomListRsp_RoomInfo::default_instance_ = new S2CGetRoomListRsp_RoomInfo();
  S2CGetRoomListRsp::default_instance_->InitAsDefaultInstance();
  S2CGetRoomListRsp_RoomInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_21004_5fS2CGetRoomListRsp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_21004_5fS2CGetRoomListRsp_2eproto {
  StaticDescriptorInitializer_21004_5fS2CGetRoomListRsp_2eproto() {
    protobuf_AddDesc_21004_5fS2CGetRoomListRsp_2eproto();
  }
} static_descriptor_initializer_21004_5fS2CGetRoomListRsp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int S2CGetRoomListRsp_RoomInfo::kIdFieldNumber;
const int S2CGetRoomListRsp_RoomInfo::kRoomNameFieldNumber;
const int S2CGetRoomListRsp_RoomInfo::kPlayerCountFieldNumber;
#endif  // !_MSC_VER

S2CGetRoomListRsp_RoomInfo::S2CGetRoomListRsp_RoomInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void S2CGetRoomListRsp_RoomInfo::InitAsDefaultInstance() {
}

S2CGetRoomListRsp_RoomInfo::S2CGetRoomListRsp_RoomInfo(const S2CGetRoomListRsp_RoomInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void S2CGetRoomListRsp_RoomInfo::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0u;
  room_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  player_count_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S2CGetRoomListRsp_RoomInfo::~S2CGetRoomListRsp_RoomInfo() {
  SharedDtor();
}

void S2CGetRoomListRsp_RoomInfo::SharedDtor() {
  if (room_name_ != &::google::protobuf::internal::kEmptyString) {
    delete room_name_;
  }
  if (this != default_instance_) {
  }
}

void S2CGetRoomListRsp_RoomInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2CGetRoomListRsp_RoomInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S2CGetRoomListRsp_RoomInfo_descriptor_;
}

const S2CGetRoomListRsp_RoomInfo& S2CGetRoomListRsp_RoomInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_21004_5fS2CGetRoomListRsp_2eproto();
  return *default_instance_;
}

S2CGetRoomListRsp_RoomInfo* S2CGetRoomListRsp_RoomInfo::default_instance_ = NULL;

S2CGetRoomListRsp_RoomInfo* S2CGetRoomListRsp_RoomInfo::New() const {
  return new S2CGetRoomListRsp_RoomInfo;
}

void S2CGetRoomListRsp_RoomInfo::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0u;
    if (has_room_name()) {
      if (room_name_ != &::google::protobuf::internal::kEmptyString) {
        room_name_->clear();
      }
    }
    player_count_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool S2CGetRoomListRsp_RoomInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_room_name;
        break;
      }

      // required string room_name = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_room_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_room_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->room_name().data(), this->room_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_player_count;
        break;
      }

      // required uint32 player_count = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_player_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &player_count_)));
          set_has_player_count();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void S2CGetRoomListRsp_RoomInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // required string room_name = 2;
  if (has_room_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->room_name().data(), this->room_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->room_name(), output);
  }

  // required uint32 player_count = 3;
  if (has_player_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->player_count(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* S2CGetRoomListRsp_RoomInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // required string room_name = 2;
  if (has_room_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->room_name().data(), this->room_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->room_name(), target);
  }

  // required uint32 player_count = 3;
  if (has_player_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->player_count(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int S2CGetRoomListRsp_RoomInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }

    // required string room_name = 2;
    if (has_room_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->room_name());
    }

    // required uint32 player_count = 3;
    if (has_player_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->player_count());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2CGetRoomListRsp_RoomInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const S2CGetRoomListRsp_RoomInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const S2CGetRoomListRsp_RoomInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S2CGetRoomListRsp_RoomInfo::MergeFrom(const S2CGetRoomListRsp_RoomInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_room_name()) {
      set_room_name(from.room_name());
    }
    if (from.has_player_count()) {
      set_player_count(from.player_count());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void S2CGetRoomListRsp_RoomInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2CGetRoomListRsp_RoomInfo::CopyFrom(const S2CGetRoomListRsp_RoomInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2CGetRoomListRsp_RoomInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void S2CGetRoomListRsp_RoomInfo::Swap(S2CGetRoomListRsp_RoomInfo* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(room_name_, other->room_name_);
    std::swap(player_count_, other->player_count_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata S2CGetRoomListRsp_RoomInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S2CGetRoomListRsp_RoomInfo_descriptor_;
  metadata.reflection = S2CGetRoomListRsp_RoomInfo_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int S2CGetRoomListRsp::kRoomListFieldNumber;
#endif  // !_MSC_VER

S2CGetRoomListRsp::S2CGetRoomListRsp()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void S2CGetRoomListRsp::InitAsDefaultInstance() {
}

S2CGetRoomListRsp::S2CGetRoomListRsp(const S2CGetRoomListRsp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void S2CGetRoomListRsp::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S2CGetRoomListRsp::~S2CGetRoomListRsp() {
  SharedDtor();
}

void S2CGetRoomListRsp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void S2CGetRoomListRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2CGetRoomListRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S2CGetRoomListRsp_descriptor_;
}

const S2CGetRoomListRsp& S2CGetRoomListRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_21004_5fS2CGetRoomListRsp_2eproto();
  return *default_instance_;
}

S2CGetRoomListRsp* S2CGetRoomListRsp::default_instance_ = NULL;

S2CGetRoomListRsp* S2CGetRoomListRsp::New() const {
  return new S2CGetRoomListRsp;
}

void S2CGetRoomListRsp::Clear() {
  room_list_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool S2CGetRoomListRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Protocol.S2CGetRoomListRsp.RoomInfo room_list = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_room_list:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_room_list()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_room_list;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void S2CGetRoomListRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .Protocol.S2CGetRoomListRsp.RoomInfo room_list = 1;
  for (int i = 0; i < this->room_list_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->room_list(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* S2CGetRoomListRsp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .Protocol.S2CGetRoomListRsp.RoomInfo room_list = 1;
  for (int i = 0; i < this->room_list_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->room_list(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int S2CGetRoomListRsp::ByteSize() const {
  int total_size = 0;

  // repeated .Protocol.S2CGetRoomListRsp.RoomInfo room_list = 1;
  total_size += 1 * this->room_list_size();
  for (int i = 0; i < this->room_list_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->room_list(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2CGetRoomListRsp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const S2CGetRoomListRsp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const S2CGetRoomListRsp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S2CGetRoomListRsp::MergeFrom(const S2CGetRoomListRsp& from) {
  GOOGLE_CHECK_NE(&from, this);
  room_list_.MergeFrom(from.room_list_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void S2CGetRoomListRsp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2CGetRoomListRsp::CopyFrom(const S2CGetRoomListRsp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2CGetRoomListRsp::IsInitialized() const {

  for (int i = 0; i < room_list_size(); i++) {
    if (!this->room_list(i).IsInitialized()) return false;
  }
  return true;
}

void S2CGetRoomListRsp::Swap(S2CGetRoomListRsp* other) {
  if (other != this) {
    room_list_.Swap(&other->room_list_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata S2CGetRoomListRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S2CGetRoomListRsp_descriptor_;
  metadata.reflection = S2CGetRoomListRsp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
