// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 21004_S2CGetRoomListRsp.proto

#ifndef PROTOBUF_21004_5fS2CGetRoomListRsp_2eproto__INCLUDED
#define PROTOBUF_21004_5fS2CGetRoomListRsp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_21004_5fS2CGetRoomListRsp_2eproto();
void protobuf_AssignDesc_21004_5fS2CGetRoomListRsp_2eproto();
void protobuf_ShutdownFile_21004_5fS2CGetRoomListRsp_2eproto();

class S2CGetRoomListRsp;
class S2CGetRoomListRsp_RoomInfo;

// ===================================================================

class S2CGetRoomListRsp_RoomInfo : public ::google::protobuf::Message {
 public:
  S2CGetRoomListRsp_RoomInfo();
  virtual ~S2CGetRoomListRsp_RoomInfo();

  S2CGetRoomListRsp_RoomInfo(const S2CGetRoomListRsp_RoomInfo& from);

  inline S2CGetRoomListRsp_RoomInfo& operator=(const S2CGetRoomListRsp_RoomInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CGetRoomListRsp_RoomInfo& default_instance();

  void Swap(S2CGetRoomListRsp_RoomInfo* other);

  // implements Message ----------------------------------------------

  S2CGetRoomListRsp_RoomInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CGetRoomListRsp_RoomInfo& from);
  void MergeFrom(const S2CGetRoomListRsp_RoomInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 room_id = 1;
  inline bool has_room_id() const;
  inline void clear_room_id();
  static const int kRoomIdFieldNumber = 1;
  inline ::google::protobuf::uint32 room_id() const;
  inline void set_room_id(::google::protobuf::uint32 value);

  // required string room_name = 2;
  inline bool has_room_name() const;
  inline void clear_room_name();
  static const int kRoomNameFieldNumber = 2;
  inline const ::std::string& room_name() const;
  inline void set_room_name(const ::std::string& value);
  inline void set_room_name(const char* value);
  inline void set_room_name(const char* value, size_t size);
  inline ::std::string* mutable_room_name();
  inline ::std::string* release_room_name();
  inline void set_allocated_room_name(::std::string* room_name);

  // required uint32 player_count = 3;
  inline bool has_player_count() const;
  inline void clear_player_count();
  static const int kPlayerCountFieldNumber = 3;
  inline ::google::protobuf::uint32 player_count() const;
  inline void set_player_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Protocol.S2CGetRoomListRsp.RoomInfo)
 private:
  inline void set_has_room_id();
  inline void clear_has_room_id();
  inline void set_has_room_name();
  inline void clear_has_room_name();
  inline void set_has_player_count();
  inline void clear_has_player_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* room_name_;
  ::google::protobuf::uint32 room_id_;
  ::google::protobuf::uint32 player_count_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_21004_5fS2CGetRoomListRsp_2eproto();
  friend void protobuf_AssignDesc_21004_5fS2CGetRoomListRsp_2eproto();
  friend void protobuf_ShutdownFile_21004_5fS2CGetRoomListRsp_2eproto();

  void InitAsDefaultInstance();
  static S2CGetRoomListRsp_RoomInfo* default_instance_;
};
// -------------------------------------------------------------------

class S2CGetRoomListRsp : public ::google::protobuf::Message {
 public:
  S2CGetRoomListRsp();
  virtual ~S2CGetRoomListRsp();

  S2CGetRoomListRsp(const S2CGetRoomListRsp& from);

  inline S2CGetRoomListRsp& operator=(const S2CGetRoomListRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CGetRoomListRsp& default_instance();

  void Swap(S2CGetRoomListRsp* other);

  // implements Message ----------------------------------------------

  S2CGetRoomListRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CGetRoomListRsp& from);
  void MergeFrom(const S2CGetRoomListRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef S2CGetRoomListRsp_RoomInfo RoomInfo;

  // accessors -------------------------------------------------------

  // repeated .Protocol.S2CGetRoomListRsp.RoomInfo room_list = 1;
  inline int room_list_size() const;
  inline void clear_room_list();
  static const int kRoomListFieldNumber = 1;
  inline const ::Protocol::S2CGetRoomListRsp_RoomInfo& room_list(int index) const;
  inline ::Protocol::S2CGetRoomListRsp_RoomInfo* mutable_room_list(int index);
  inline ::Protocol::S2CGetRoomListRsp_RoomInfo* add_room_list();
  inline const ::google::protobuf::RepeatedPtrField< ::Protocol::S2CGetRoomListRsp_RoomInfo >&
      room_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::Protocol::S2CGetRoomListRsp_RoomInfo >*
      mutable_room_list();

  // @@protoc_insertion_point(class_scope:Protocol.S2CGetRoomListRsp)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::Protocol::S2CGetRoomListRsp_RoomInfo > room_list_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_21004_5fS2CGetRoomListRsp_2eproto();
  friend void protobuf_AssignDesc_21004_5fS2CGetRoomListRsp_2eproto();
  friend void protobuf_ShutdownFile_21004_5fS2CGetRoomListRsp_2eproto();

  void InitAsDefaultInstance();
  static S2CGetRoomListRsp* default_instance_;
};
// ===================================================================


// ===================================================================

// S2CGetRoomListRsp_RoomInfo

// required uint32 room_id = 1;
inline bool S2CGetRoomListRsp_RoomInfo::has_room_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CGetRoomListRsp_RoomInfo::set_has_room_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CGetRoomListRsp_RoomInfo::clear_has_room_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CGetRoomListRsp_RoomInfo::clear_room_id() {
  room_id_ = 0u;
  clear_has_room_id();
}
inline ::google::protobuf::uint32 S2CGetRoomListRsp_RoomInfo::room_id() const {
  return room_id_;
}
inline void S2CGetRoomListRsp_RoomInfo::set_room_id(::google::protobuf::uint32 value) {
  set_has_room_id();
  room_id_ = value;
}

// required string room_name = 2;
inline bool S2CGetRoomListRsp_RoomInfo::has_room_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CGetRoomListRsp_RoomInfo::set_has_room_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CGetRoomListRsp_RoomInfo::clear_has_room_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CGetRoomListRsp_RoomInfo::clear_room_name() {
  if (room_name_ != &::google::protobuf::internal::kEmptyString) {
    room_name_->clear();
  }
  clear_has_room_name();
}
inline const ::std::string& S2CGetRoomListRsp_RoomInfo::room_name() const {
  return *room_name_;
}
inline void S2CGetRoomListRsp_RoomInfo::set_room_name(const ::std::string& value) {
  set_has_room_name();
  if (room_name_ == &::google::protobuf::internal::kEmptyString) {
    room_name_ = new ::std::string;
  }
  room_name_->assign(value);
}
inline void S2CGetRoomListRsp_RoomInfo::set_room_name(const char* value) {
  set_has_room_name();
  if (room_name_ == &::google::protobuf::internal::kEmptyString) {
    room_name_ = new ::std::string;
  }
  room_name_->assign(value);
}
inline void S2CGetRoomListRsp_RoomInfo::set_room_name(const char* value, size_t size) {
  set_has_room_name();
  if (room_name_ == &::google::protobuf::internal::kEmptyString) {
    room_name_ = new ::std::string;
  }
  room_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* S2CGetRoomListRsp_RoomInfo::mutable_room_name() {
  set_has_room_name();
  if (room_name_ == &::google::protobuf::internal::kEmptyString) {
    room_name_ = new ::std::string;
  }
  return room_name_;
}
inline ::std::string* S2CGetRoomListRsp_RoomInfo::release_room_name() {
  clear_has_room_name();
  if (room_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = room_name_;
    room_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void S2CGetRoomListRsp_RoomInfo::set_allocated_room_name(::std::string* room_name) {
  if (room_name_ != &::google::protobuf::internal::kEmptyString) {
    delete room_name_;
  }
  if (room_name) {
    set_has_room_name();
    room_name_ = room_name;
  } else {
    clear_has_room_name();
    room_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required uint32 player_count = 3;
inline bool S2CGetRoomListRsp_RoomInfo::has_player_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void S2CGetRoomListRsp_RoomInfo::set_has_player_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void S2CGetRoomListRsp_RoomInfo::clear_has_player_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void S2CGetRoomListRsp_RoomInfo::clear_player_count() {
  player_count_ = 0u;
  clear_has_player_count();
}
inline ::google::protobuf::uint32 S2CGetRoomListRsp_RoomInfo::player_count() const {
  return player_count_;
}
inline void S2CGetRoomListRsp_RoomInfo::set_player_count(::google::protobuf::uint32 value) {
  set_has_player_count();
  player_count_ = value;
}

// -------------------------------------------------------------------

// S2CGetRoomListRsp

// repeated .Protocol.S2CGetRoomListRsp.RoomInfo room_list = 1;
inline int S2CGetRoomListRsp::room_list_size() const {
  return room_list_.size();
}
inline void S2CGetRoomListRsp::clear_room_list() {
  room_list_.Clear();
}
inline const ::Protocol::S2CGetRoomListRsp_RoomInfo& S2CGetRoomListRsp::room_list(int index) const {
  return room_list_.Get(index);
}
inline ::Protocol::S2CGetRoomListRsp_RoomInfo* S2CGetRoomListRsp::mutable_room_list(int index) {
  return room_list_.Mutable(index);
}
inline ::Protocol::S2CGetRoomListRsp_RoomInfo* S2CGetRoomListRsp::add_room_list() {
  return room_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Protocol::S2CGetRoomListRsp_RoomInfo >&
S2CGetRoomListRsp::room_list() const {
  return room_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::Protocol::S2CGetRoomListRsp_RoomInfo >*
S2CGetRoomListRsp::mutable_room_list() {
  return &room_list_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_21004_5fS2CGetRoomListRsp_2eproto__INCLUDED
