// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 21011_C2SLeaveRoomReq.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "21011_C2SLeaveRoomReq.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* C2SLeaveRoomReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  C2SLeaveRoomReq_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_21011_5fC2SLeaveRoomReq_2eproto() {
  protobuf_AddDesc_21011_5fC2SLeaveRoomReq_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "21011_C2SLeaveRoomReq.proto");
  GOOGLE_CHECK(file != NULL);
  C2SLeaveRoomReq_descriptor_ = file->message_type(0);
  static const int C2SLeaveRoomReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2SLeaveRoomReq, room_id_),
  };
  C2SLeaveRoomReq_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      C2SLeaveRoomReq_descriptor_,
      C2SLeaveRoomReq::default_instance_,
      C2SLeaveRoomReq_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2SLeaveRoomReq, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2SLeaveRoomReq, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(C2SLeaveRoomReq));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_21011_5fC2SLeaveRoomReq_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    C2SLeaveRoomReq_descriptor_, &C2SLeaveRoomReq::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_21011_5fC2SLeaveRoomReq_2eproto() {
  delete C2SLeaveRoomReq::default_instance_;
  delete C2SLeaveRoomReq_reflection_;
}

void protobuf_AddDesc_21011_5fC2SLeaveRoomReq_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\03321011_C2SLeaveRoomReq.proto\022\010Protocol\""
    "\"\n\017C2SLeaveRoomReq\022\017\n\007room_id\030\001 \002(\r", 75);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "21011_C2SLeaveRoomReq.proto", &protobuf_RegisterTypes);
  C2SLeaveRoomReq::default_instance_ = new C2SLeaveRoomReq();
  C2SLeaveRoomReq::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_21011_5fC2SLeaveRoomReq_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_21011_5fC2SLeaveRoomReq_2eproto {
  StaticDescriptorInitializer_21011_5fC2SLeaveRoomReq_2eproto() {
    protobuf_AddDesc_21011_5fC2SLeaveRoomReq_2eproto();
  }
} static_descriptor_initializer_21011_5fC2SLeaveRoomReq_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int C2SLeaveRoomReq::kRoomIdFieldNumber;
#endif  // !_MSC_VER

C2SLeaveRoomReq::C2SLeaveRoomReq()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void C2SLeaveRoomReq::InitAsDefaultInstance() {
}

C2SLeaveRoomReq::C2SLeaveRoomReq(const C2SLeaveRoomReq& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void C2SLeaveRoomReq::SharedCtor() {
  _cached_size_ = 0;
  room_id_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

C2SLeaveRoomReq::~C2SLeaveRoomReq() {
  SharedDtor();
}

void C2SLeaveRoomReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void C2SLeaveRoomReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* C2SLeaveRoomReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return C2SLeaveRoomReq_descriptor_;
}

const C2SLeaveRoomReq& C2SLeaveRoomReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_21011_5fC2SLeaveRoomReq_2eproto();
  return *default_instance_;
}

C2SLeaveRoomReq* C2SLeaveRoomReq::default_instance_ = NULL;

C2SLeaveRoomReq* C2SLeaveRoomReq::New() const {
  return new C2SLeaveRoomReq;
}

void C2SLeaveRoomReq::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    room_id_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool C2SLeaveRoomReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 room_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &room_id_)));
          set_has_room_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void C2SLeaveRoomReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 room_id = 1;
  if (has_room_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->room_id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* C2SLeaveRoomReq::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 room_id = 1;
  if (has_room_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->room_id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int C2SLeaveRoomReq::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 room_id = 1;
    if (has_room_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->room_id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void C2SLeaveRoomReq::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const C2SLeaveRoomReq* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const C2SLeaveRoomReq*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void C2SLeaveRoomReq::MergeFrom(const C2SLeaveRoomReq& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_room_id()) {
      set_room_id(from.room_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void C2SLeaveRoomReq::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2SLeaveRoomReq::CopyFrom(const C2SLeaveRoomReq& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2SLeaveRoomReq::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void C2SLeaveRoomReq::Swap(C2SLeaveRoomReq* other) {
  if (other != this) {
    std::swap(room_id_, other->room_id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata C2SLeaveRoomReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = C2SLeaveRoomReq_descriptor_;
  metadata.reflection = C2SLeaveRoomReq_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
