// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 21013_C2SKickPlayerReq.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "21013_C2SKickPlayerReq.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* C2SKickPlayerReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  C2SKickPlayerReq_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_21013_5fC2SKickPlayerReq_2eproto() {
  protobuf_AddDesc_21013_5fC2SKickPlayerReq_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "21013_C2SKickPlayerReq.proto");
  GOOGLE_CHECK(file != NULL);
  C2SKickPlayerReq_descriptor_ = file->message_type(0);
  static const int C2SKickPlayerReq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2SKickPlayerReq, room_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2SKickPlayerReq, kicked_palyer_guid_),
  };
  C2SKickPlayerReq_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      C2SKickPlayerReq_descriptor_,
      C2SKickPlayerReq::default_instance_,
      C2SKickPlayerReq_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2SKickPlayerReq, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2SKickPlayerReq, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(C2SKickPlayerReq));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_21013_5fC2SKickPlayerReq_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    C2SKickPlayerReq_descriptor_, &C2SKickPlayerReq::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_21013_5fC2SKickPlayerReq_2eproto() {
  delete C2SKickPlayerReq::default_instance_;
  delete C2SKickPlayerReq_reflection_;
}

void protobuf_AddDesc_21013_5fC2SKickPlayerReq_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\03421013_C2SKickPlayerReq.proto\022\010Protocol"
    "\"\?\n\020C2SKickPlayerReq\022\017\n\007room_id\030\001 \002(\r\022\032\n"
    "\022kicked_palyer_guid\030\002 \002(\004", 105);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "21013_C2SKickPlayerReq.proto", &protobuf_RegisterTypes);
  C2SKickPlayerReq::default_instance_ = new C2SKickPlayerReq();
  C2SKickPlayerReq::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_21013_5fC2SKickPlayerReq_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_21013_5fC2SKickPlayerReq_2eproto {
  StaticDescriptorInitializer_21013_5fC2SKickPlayerReq_2eproto() {
    protobuf_AddDesc_21013_5fC2SKickPlayerReq_2eproto();
  }
} static_descriptor_initializer_21013_5fC2SKickPlayerReq_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int C2SKickPlayerReq::kRoomIdFieldNumber;
const int C2SKickPlayerReq::kKickedPalyerGuidFieldNumber;
#endif  // !_MSC_VER

C2SKickPlayerReq::C2SKickPlayerReq()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void C2SKickPlayerReq::InitAsDefaultInstance() {
}

C2SKickPlayerReq::C2SKickPlayerReq(const C2SKickPlayerReq& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void C2SKickPlayerReq::SharedCtor() {
  _cached_size_ = 0;
  room_id_ = 0u;
  kicked_palyer_guid_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

C2SKickPlayerReq::~C2SKickPlayerReq() {
  SharedDtor();
}

void C2SKickPlayerReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void C2SKickPlayerReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* C2SKickPlayerReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return C2SKickPlayerReq_descriptor_;
}

const C2SKickPlayerReq& C2SKickPlayerReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_21013_5fC2SKickPlayerReq_2eproto();
  return *default_instance_;
}

C2SKickPlayerReq* C2SKickPlayerReq::default_instance_ = NULL;

C2SKickPlayerReq* C2SKickPlayerReq::New() const {
  return new C2SKickPlayerReq;
}

void C2SKickPlayerReq::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    room_id_ = 0u;
    kicked_palyer_guid_ = GOOGLE_ULONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool C2SKickPlayerReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 room_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &room_id_)));
          set_has_room_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_kicked_palyer_guid;
        break;
      }

      // required uint64 kicked_palyer_guid = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_kicked_palyer_guid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &kicked_palyer_guid_)));
          set_has_kicked_palyer_guid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void C2SKickPlayerReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 room_id = 1;
  if (has_room_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->room_id(), output);
  }

  // required uint64 kicked_palyer_guid = 2;
  if (has_kicked_palyer_guid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->kicked_palyer_guid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* C2SKickPlayerReq::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 room_id = 1;
  if (has_room_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->room_id(), target);
  }

  // required uint64 kicked_palyer_guid = 2;
  if (has_kicked_palyer_guid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->kicked_palyer_guid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int C2SKickPlayerReq::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 room_id = 1;
    if (has_room_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->room_id());
    }

    // required uint64 kicked_palyer_guid = 2;
    if (has_kicked_palyer_guid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->kicked_palyer_guid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void C2SKickPlayerReq::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const C2SKickPlayerReq* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const C2SKickPlayerReq*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void C2SKickPlayerReq::MergeFrom(const C2SKickPlayerReq& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_room_id()) {
      set_room_id(from.room_id());
    }
    if (from.has_kicked_palyer_guid()) {
      set_kicked_palyer_guid(from.kicked_palyer_guid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void C2SKickPlayerReq::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2SKickPlayerReq::CopyFrom(const C2SKickPlayerReq& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2SKickPlayerReq::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void C2SKickPlayerReq::Swap(C2SKickPlayerReq* other) {
  if (other != this) {
    std::swap(room_id_, other->room_id_);
    std::swap(kicked_palyer_guid_, other->kicked_palyer_guid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata C2SKickPlayerReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = C2SKickPlayerReq_descriptor_;
  metadata.reflection = C2SKickPlayerReq_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
