// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 22002_S2CTransferAccountsRsp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "22002_S2CTransferAccountsRsp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* S2CTransferAccountsRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S2CTransferAccountsRsp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_22002_5fS2CTransferAccountsRsp_2eproto() {
  protobuf_AddDesc_22002_5fS2CTransferAccountsRsp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "22002_S2CTransferAccountsRsp.proto");
  GOOGLE_CHECK(file != NULL);
  S2CTransferAccountsRsp_descriptor_ = file->message_type(0);
  static const int S2CTransferAccountsRsp_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CTransferAccountsRsp, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CTransferAccountsRsp, content_),
  };
  S2CTransferAccountsRsp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      S2CTransferAccountsRsp_descriptor_,
      S2CTransferAccountsRsp::default_instance_,
      S2CTransferAccountsRsp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CTransferAccountsRsp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CTransferAccountsRsp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(S2CTransferAccountsRsp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_22002_5fS2CTransferAccountsRsp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    S2CTransferAccountsRsp_descriptor_, &S2CTransferAccountsRsp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_22002_5fS2CTransferAccountsRsp_2eproto() {
  delete S2CTransferAccountsRsp::default_instance_;
  delete S2CTransferAccountsRsp_reflection_;
}

void protobuf_AddDesc_22002_5fS2CTransferAccountsRsp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\"22002_S2CTransferAccountsRsp.proto\022\010Pr"
    "otocol\"9\n\026S2CTransferAccountsRsp\022\016\n\006resu"
    "lt\030\001 \002(\005\022\017\n\007content\030\002 \002(\014", 105);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "22002_S2CTransferAccountsRsp.proto", &protobuf_RegisterTypes);
  S2CTransferAccountsRsp::default_instance_ = new S2CTransferAccountsRsp();
  S2CTransferAccountsRsp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_22002_5fS2CTransferAccountsRsp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_22002_5fS2CTransferAccountsRsp_2eproto {
  StaticDescriptorInitializer_22002_5fS2CTransferAccountsRsp_2eproto() {
    protobuf_AddDesc_22002_5fS2CTransferAccountsRsp_2eproto();
  }
} static_descriptor_initializer_22002_5fS2CTransferAccountsRsp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int S2CTransferAccountsRsp::kResultFieldNumber;
const int S2CTransferAccountsRsp::kContentFieldNumber;
#endif  // !_MSC_VER

S2CTransferAccountsRsp::S2CTransferAccountsRsp()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void S2CTransferAccountsRsp::InitAsDefaultInstance() {
}

S2CTransferAccountsRsp::S2CTransferAccountsRsp(const S2CTransferAccountsRsp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void S2CTransferAccountsRsp::SharedCtor() {
  _cached_size_ = 0;
  result_ = 0;
  content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S2CTransferAccountsRsp::~S2CTransferAccountsRsp() {
  SharedDtor();
}

void S2CTransferAccountsRsp::SharedDtor() {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    delete content_;
  }
  if (this != default_instance_) {
  }
}

void S2CTransferAccountsRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2CTransferAccountsRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S2CTransferAccountsRsp_descriptor_;
}

const S2CTransferAccountsRsp& S2CTransferAccountsRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_22002_5fS2CTransferAccountsRsp_2eproto();
  return *default_instance_;
}

S2CTransferAccountsRsp* S2CTransferAccountsRsp::default_instance_ = NULL;

S2CTransferAccountsRsp* S2CTransferAccountsRsp::New() const {
  return new S2CTransferAccountsRsp;
}

void S2CTransferAccountsRsp::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    result_ = 0;
    if (has_content()) {
      if (content_ != &::google::protobuf::internal::kEmptyString) {
        content_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool S2CTransferAccountsRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 result = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));
          set_has_result();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_content;
        break;
      }

      // required bytes content = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_content:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_content()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void S2CTransferAccountsRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 result = 1;
  if (has_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->result(), output);
  }

  // required bytes content = 2;
  if (has_content()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->content(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* S2CTransferAccountsRsp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 result = 1;
  if (has_result()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->result(), target);
  }

  // required bytes content = 2;
  if (has_content()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->content(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int S2CTransferAccountsRsp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 result = 1;
    if (has_result()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->result());
    }

    // required bytes content = 2;
    if (has_content()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->content());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2CTransferAccountsRsp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const S2CTransferAccountsRsp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const S2CTransferAccountsRsp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S2CTransferAccountsRsp::MergeFrom(const S2CTransferAccountsRsp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_result()) {
      set_result(from.result());
    }
    if (from.has_content()) {
      set_content(from.content());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void S2CTransferAccountsRsp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2CTransferAccountsRsp::CopyFrom(const S2CTransferAccountsRsp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2CTransferAccountsRsp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void S2CTransferAccountsRsp::Swap(S2CTransferAccountsRsp* other) {
  if (other != this) {
    std::swap(result_, other->result_);
    std::swap(content_, other->content_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata S2CTransferAccountsRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S2CTransferAccountsRsp_descriptor_;
  metadata.reflection = S2CTransferAccountsRsp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
