// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 22002_S2CTransferAccountsRsp.proto

#ifndef PROTOBUF_22002_5fS2CTransferAccountsRsp_2eproto__INCLUDED
#define PROTOBUF_22002_5fS2CTransferAccountsRsp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_22002_5fS2CTransferAccountsRsp_2eproto();
void protobuf_AssignDesc_22002_5fS2CTransferAccountsRsp_2eproto();
void protobuf_ShutdownFile_22002_5fS2CTransferAccountsRsp_2eproto();

class S2CTransferAccountsRsp;

// ===================================================================

class S2CTransferAccountsRsp : public ::google::protobuf::Message {
 public:
  S2CTransferAccountsRsp();
  virtual ~S2CTransferAccountsRsp();

  S2CTransferAccountsRsp(const S2CTransferAccountsRsp& from);

  inline S2CTransferAccountsRsp& operator=(const S2CTransferAccountsRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CTransferAccountsRsp& default_instance();

  void Swap(S2CTransferAccountsRsp* other);

  // implements Message ----------------------------------------------

  S2CTransferAccountsRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CTransferAccountsRsp& from);
  void MergeFrom(const S2CTransferAccountsRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // required bytes content = 2;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 2;
  inline const ::std::string& content() const;
  inline void set_content(const ::std::string& value);
  inline void set_content(const char* value);
  inline void set_content(const void* value, size_t size);
  inline ::std::string* mutable_content();
  inline ::std::string* release_content();
  inline void set_allocated_content(::std::string* content);

  // @@protoc_insertion_point(class_scope:Protocol.S2CTransferAccountsRsp)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_content();
  inline void clear_has_content();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* content_;
  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_22002_5fS2CTransferAccountsRsp_2eproto();
  friend void protobuf_AssignDesc_22002_5fS2CTransferAccountsRsp_2eproto();
  friend void protobuf_ShutdownFile_22002_5fS2CTransferAccountsRsp_2eproto();

  void InitAsDefaultInstance();
  static S2CTransferAccountsRsp* default_instance_;
};
// ===================================================================


// ===================================================================

// S2CTransferAccountsRsp

// required int32 result = 1;
inline bool S2CTransferAccountsRsp::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CTransferAccountsRsp::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CTransferAccountsRsp::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CTransferAccountsRsp::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 S2CTransferAccountsRsp::result() const {
  return result_;
}
inline void S2CTransferAccountsRsp::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// required bytes content = 2;
inline bool S2CTransferAccountsRsp::has_content() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CTransferAccountsRsp::set_has_content() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CTransferAccountsRsp::clear_has_content() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CTransferAccountsRsp::clear_content() {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    content_->clear();
  }
  clear_has_content();
}
inline const ::std::string& S2CTransferAccountsRsp::content() const {
  return *content_;
}
inline void S2CTransferAccountsRsp::set_content(const ::std::string& value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void S2CTransferAccountsRsp::set_content(const char* value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void S2CTransferAccountsRsp::set_content(const void* value, size_t size) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* S2CTransferAccountsRsp::mutable_content() {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  return content_;
}
inline ::std::string* S2CTransferAccountsRsp::release_content() {
  clear_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = content_;
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void S2CTransferAccountsRsp::set_allocated_content(::std::string* content) {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    delete content_;
  }
  if (content) {
    set_has_content();
    content_ = content;
  } else {
    clear_has_content();
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_22002_5fS2CTransferAccountsRsp_2eproto__INCLUDED
