// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 22001_C2STransferAccountsReq.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "22001_C2STransferAccountsReq.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* C2STransferAccountsReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  C2STransferAccountsReq_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_22001_5fC2STransferAccountsReq_2eproto() {
  protobuf_AddDesc_22001_5fC2STransferAccountsReq_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "22001_C2STransferAccountsReq.proto");
  GOOGLE_CHECK(file != NULL);
  C2STransferAccountsReq_descriptor_ = file->message_type(0);
  static const int C2STransferAccountsReq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2STransferAccountsReq, money_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2STransferAccountsReq, money_count_),
  };
  C2STransferAccountsReq_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      C2STransferAccountsReq_descriptor_,
      C2STransferAccountsReq::default_instance_,
      C2STransferAccountsReq_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2STransferAccountsReq, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2STransferAccountsReq, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(C2STransferAccountsReq));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_22001_5fC2STransferAccountsReq_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    C2STransferAccountsReq_descriptor_, &C2STransferAccountsReq::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_22001_5fC2STransferAccountsReq_2eproto() {
  delete C2STransferAccountsReq::default_instance_;
  delete C2STransferAccountsReq_reflection_;
}

void protobuf_AddDesc_22001_5fC2STransferAccountsReq_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\"22001_C2STransferAccountsReq.proto\022\010Pr"
    "otocol\"A\n\026C2STransferAccountsReq\022\022\n\nmone"
    "y_type\030\001 \002(\005\022\023\n\013money_count\030\002 \002(\005", 113);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "22001_C2STransferAccountsReq.proto", &protobuf_RegisterTypes);
  C2STransferAccountsReq::default_instance_ = new C2STransferAccountsReq();
  C2STransferAccountsReq::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_22001_5fC2STransferAccountsReq_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_22001_5fC2STransferAccountsReq_2eproto {
  StaticDescriptorInitializer_22001_5fC2STransferAccountsReq_2eproto() {
    protobuf_AddDesc_22001_5fC2STransferAccountsReq_2eproto();
  }
} static_descriptor_initializer_22001_5fC2STransferAccountsReq_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int C2STransferAccountsReq::kMoneyTypeFieldNumber;
const int C2STransferAccountsReq::kMoneyCountFieldNumber;
#endif  // !_MSC_VER

C2STransferAccountsReq::C2STransferAccountsReq()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void C2STransferAccountsReq::InitAsDefaultInstance() {
}

C2STransferAccountsReq::C2STransferAccountsReq(const C2STransferAccountsReq& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void C2STransferAccountsReq::SharedCtor() {
  _cached_size_ = 0;
  money_type_ = 0;
  money_count_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

C2STransferAccountsReq::~C2STransferAccountsReq() {
  SharedDtor();
}

void C2STransferAccountsReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void C2STransferAccountsReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* C2STransferAccountsReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return C2STransferAccountsReq_descriptor_;
}

const C2STransferAccountsReq& C2STransferAccountsReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_22001_5fC2STransferAccountsReq_2eproto();
  return *default_instance_;
}

C2STransferAccountsReq* C2STransferAccountsReq::default_instance_ = NULL;

C2STransferAccountsReq* C2STransferAccountsReq::New() const {
  return new C2STransferAccountsReq;
}

void C2STransferAccountsReq::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    money_type_ = 0;
    money_count_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool C2STransferAccountsReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 money_type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &money_type_)));
          set_has_money_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_money_count;
        break;
      }

      // required int32 money_count = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_money_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &money_count_)));
          set_has_money_count();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void C2STransferAccountsReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 money_type = 1;
  if (has_money_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->money_type(), output);
  }

  // required int32 money_count = 2;
  if (has_money_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->money_count(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* C2STransferAccountsReq::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 money_type = 1;
  if (has_money_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->money_type(), target);
  }

  // required int32 money_count = 2;
  if (has_money_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->money_count(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int C2STransferAccountsReq::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 money_type = 1;
    if (has_money_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->money_type());
    }

    // required int32 money_count = 2;
    if (has_money_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->money_count());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void C2STransferAccountsReq::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const C2STransferAccountsReq* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const C2STransferAccountsReq*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void C2STransferAccountsReq::MergeFrom(const C2STransferAccountsReq& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_money_type()) {
      set_money_type(from.money_type());
    }
    if (from.has_money_count()) {
      set_money_count(from.money_count());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void C2STransferAccountsReq::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2STransferAccountsReq::CopyFrom(const C2STransferAccountsReq& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2STransferAccountsReq::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void C2STransferAccountsReq::Swap(C2STransferAccountsReq* other) {
  if (other != this) {
    std::swap(money_type_, other->money_type_);
    std::swap(money_count_, other->money_count_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata C2STransferAccountsReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = C2STransferAccountsReq_descriptor_;
  metadata.reflection = C2STransferAccountsReq_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
