// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 99991_S2CErrorEx.proto

#ifndef PROTOBUF_99991_5fS2CErrorEx_2eproto__INCLUDED
#define PROTOBUF_99991_5fS2CErrorEx_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_99991_5fS2CErrorEx_2eproto();
void protobuf_AssignDesc_99991_5fS2CErrorEx_2eproto();
void protobuf_ShutdownFile_99991_5fS2CErrorEx_2eproto();

class S2CErrorEx;

// ===================================================================

class S2CErrorEx : public ::google::protobuf::Message {
 public:
  S2CErrorEx();
  virtual ~S2CErrorEx();

  S2CErrorEx(const S2CErrorEx& from);

  inline S2CErrorEx& operator=(const S2CErrorEx& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CErrorEx& default_instance();

  void Swap(S2CErrorEx* other);

  // implements Message ----------------------------------------------

  S2CErrorEx* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CErrorEx& from);
  void MergeFrom(const S2CErrorEx& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::uint32 error_code() const;
  inline void set_error_code(::google::protobuf::uint32 value);

  // optional bytes error_reason = 2;
  inline bool has_error_reason() const;
  inline void clear_error_reason();
  static const int kErrorReasonFieldNumber = 2;
  inline const ::std::string& error_reason() const;
  inline void set_error_reason(const ::std::string& value);
  inline void set_error_reason(const char* value);
  inline void set_error_reason(const void* value, size_t size);
  inline ::std::string* mutable_error_reason();
  inline ::std::string* release_error_reason();
  inline void set_allocated_error_reason(::std::string* error_reason);

  // @@protoc_insertion_point(class_scope:Protocol.S2CErrorEx)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();
  inline void set_has_error_reason();
  inline void clear_has_error_reason();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* error_reason_;
  ::google::protobuf::uint32 error_code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_99991_5fS2CErrorEx_2eproto();
  friend void protobuf_AssignDesc_99991_5fS2CErrorEx_2eproto();
  friend void protobuf_ShutdownFile_99991_5fS2CErrorEx_2eproto();

  void InitAsDefaultInstance();
  static S2CErrorEx* default_instance_;
};
// ===================================================================


// ===================================================================

// S2CErrorEx

// required uint32 error_code = 1;
inline bool S2CErrorEx::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CErrorEx::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CErrorEx::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CErrorEx::clear_error_code() {
  error_code_ = 0u;
  clear_has_error_code();
}
inline ::google::protobuf::uint32 S2CErrorEx::error_code() const {
  return error_code_;
}
inline void S2CErrorEx::set_error_code(::google::protobuf::uint32 value) {
  set_has_error_code();
  error_code_ = value;
}

// optional bytes error_reason = 2;
inline bool S2CErrorEx::has_error_reason() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CErrorEx::set_has_error_reason() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CErrorEx::clear_has_error_reason() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CErrorEx::clear_error_reason() {
  if (error_reason_ != &::google::protobuf::internal::kEmptyString) {
    error_reason_->clear();
  }
  clear_has_error_reason();
}
inline const ::std::string& S2CErrorEx::error_reason() const {
  return *error_reason_;
}
inline void S2CErrorEx::set_error_reason(const ::std::string& value) {
  set_has_error_reason();
  if (error_reason_ == &::google::protobuf::internal::kEmptyString) {
    error_reason_ = new ::std::string;
  }
  error_reason_->assign(value);
}
inline void S2CErrorEx::set_error_reason(const char* value) {
  set_has_error_reason();
  if (error_reason_ == &::google::protobuf::internal::kEmptyString) {
    error_reason_ = new ::std::string;
  }
  error_reason_->assign(value);
}
inline void S2CErrorEx::set_error_reason(const void* value, size_t size) {
  set_has_error_reason();
  if (error_reason_ == &::google::protobuf::internal::kEmptyString) {
    error_reason_ = new ::std::string;
  }
  error_reason_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* S2CErrorEx::mutable_error_reason() {
  set_has_error_reason();
  if (error_reason_ == &::google::protobuf::internal::kEmptyString) {
    error_reason_ = new ::std::string;
  }
  return error_reason_;
}
inline ::std::string* S2CErrorEx::release_error_reason() {
  clear_has_error_reason();
  if (error_reason_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = error_reason_;
    error_reason_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void S2CErrorEx::set_allocated_error_reason(::std::string* error_reason) {
  if (error_reason_ != &::google::protobuf::internal::kEmptyString) {
    delete error_reason_;
  }
  if (error_reason) {
    set_has_error_reason();
    error_reason_ = error_reason;
  } else {
    clear_has_error_reason();
    error_reason_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_99991_5fS2CErrorEx_2eproto__INCLUDED
