// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 99991_S2CErrorEx.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "99991_S2CErrorEx.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* S2CErrorEx_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S2CErrorEx_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_99991_5fS2CErrorEx_2eproto() {
  protobuf_AddDesc_99991_5fS2CErrorEx_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "99991_S2CErrorEx.proto");
  GOOGLE_CHECK(file != NULL);
  S2CErrorEx_descriptor_ = file->message_type(0);
  static const int S2CErrorEx_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CErrorEx, error_code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CErrorEx, error_reason_),
  };
  S2CErrorEx_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      S2CErrorEx_descriptor_,
      S2CErrorEx::default_instance_,
      S2CErrorEx_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CErrorEx, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CErrorEx, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(S2CErrorEx));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_99991_5fS2CErrorEx_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    S2CErrorEx_descriptor_, &S2CErrorEx::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_99991_5fS2CErrorEx_2eproto() {
  delete S2CErrorEx::default_instance_;
  delete S2CErrorEx_reflection_;
}

void protobuf_AddDesc_99991_5fS2CErrorEx_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\02699991_S2CErrorEx.proto\022\010Protocol\"6\n\nS2"
    "CErrorEx\022\022\n\nerror_code\030\001 \002(\r\022\024\n\014error_re"
    "ason\030\002 \001(\014", 90);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "99991_S2CErrorEx.proto", &protobuf_RegisterTypes);
  S2CErrorEx::default_instance_ = new S2CErrorEx();
  S2CErrorEx::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_99991_5fS2CErrorEx_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_99991_5fS2CErrorEx_2eproto {
  StaticDescriptorInitializer_99991_5fS2CErrorEx_2eproto() {
    protobuf_AddDesc_99991_5fS2CErrorEx_2eproto();
  }
} static_descriptor_initializer_99991_5fS2CErrorEx_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int S2CErrorEx::kErrorCodeFieldNumber;
const int S2CErrorEx::kErrorReasonFieldNumber;
#endif  // !_MSC_VER

S2CErrorEx::S2CErrorEx()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void S2CErrorEx::InitAsDefaultInstance() {
}

S2CErrorEx::S2CErrorEx(const S2CErrorEx& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void S2CErrorEx::SharedCtor() {
  _cached_size_ = 0;
  error_code_ = 0u;
  error_reason_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S2CErrorEx::~S2CErrorEx() {
  SharedDtor();
}

void S2CErrorEx::SharedDtor() {
  if (error_reason_ != &::google::protobuf::internal::kEmptyString) {
    delete error_reason_;
  }
  if (this != default_instance_) {
  }
}

void S2CErrorEx::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2CErrorEx::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S2CErrorEx_descriptor_;
}

const S2CErrorEx& S2CErrorEx::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_99991_5fS2CErrorEx_2eproto();
  return *default_instance_;
}

S2CErrorEx* S2CErrorEx::default_instance_ = NULL;

S2CErrorEx* S2CErrorEx::New() const {
  return new S2CErrorEx;
}

void S2CErrorEx::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    error_code_ = 0u;
    if (has_error_reason()) {
      if (error_reason_ != &::google::protobuf::internal::kEmptyString) {
        error_reason_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool S2CErrorEx::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 error_code = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &error_code_)));
          set_has_error_code();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_error_reason;
        break;
      }

      // optional bytes error_reason = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_error_reason:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_error_reason()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void S2CErrorEx::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 error_code = 1;
  if (has_error_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->error_code(), output);
  }

  // optional bytes error_reason = 2;
  if (has_error_reason()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->error_reason(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* S2CErrorEx::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 error_code = 1;
  if (has_error_code()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->error_code(), target);
  }

  // optional bytes error_reason = 2;
  if (has_error_reason()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->error_reason(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int S2CErrorEx::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 error_code = 1;
    if (has_error_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->error_code());
    }

    // optional bytes error_reason = 2;
    if (has_error_reason()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->error_reason());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2CErrorEx::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const S2CErrorEx* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const S2CErrorEx*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S2CErrorEx::MergeFrom(const S2CErrorEx& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_error_code()) {
      set_error_code(from.error_code());
    }
    if (from.has_error_reason()) {
      set_error_reason(from.error_reason());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void S2CErrorEx::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2CErrorEx::CopyFrom(const S2CErrorEx& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2CErrorEx::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void S2CErrorEx::Swap(S2CErrorEx* other) {
  if (other != this) {
    std::swap(error_code_, other->error_code_);
    std::swap(error_reason_, other->error_reason_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata S2CErrorEx::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S2CErrorEx_descriptor_;
  metadata.reflection = S2CErrorEx_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
