// Generated by Zeus, DO NOT EDIT! 
// DateTime : 2013/11/14 ÷‹Àƒ 18:09:34  

#ifndef __PROTOBUF_H__ 
#define __PROTOBUF_H__ 

#include "protocol/10000_C2SLoginReq.pb.h" 
#include "protocol/10001_S2CLoginRsp.pb.h" 
#include "protocol/10002_C2SRegisterReq.pb.h" 
#include "protocol/10003_S2CRegisterRsp.pb.h" 
#include "protocol/15000_C2SGetPlayerProfileReq.pb.h" 
#include "protocol/15001_S2CGetPlayerProfileRsp.pb.h" 
#include "protocol/20000_C2SChatMessageReq.pb.h" 
#include "protocol/20001_S2CChatMessageNotify.pb.h" 
#include "protocol/21001_C2SRoomCreateReq.pb.h" 
#include "protocol/21002_S2CRoomCreateRsp.pb.h" 
#include "protocol/21003_C2SGetRoomListReq.pb.h" 
#include "protocol/21004_S2CGetRoomListRsp.pb.h" 
#include "protocol/21005_C2SRoomCancleReq.pb.h" 
#include "protocol/21006_S2CRoomCancleNotify.pb.h" 
#include "protocol/21007_C2SRoomInfoChangeReq.pb.h" 
#include "protocol/21008_S2CRoomInfoChangeNotify.pb.h" 
#include "protocol/21009_C2SEnterRoomReq.pb.h" 
#include "protocol/21010_S2CEnterRoomRsp.pb.h" 
#include "protocol/21011_C2SLeaveRoomReq.pb.h" 
#include "protocol/21012_S2CPlayerLeaveRoomNotify.pb.h" 
#include "protocol/21013_C2SKickPlayerReq.pb.h" 
#include "protocol/21014_S2CRoomKickedNotify.pb.h" 
#include "protocol/21015_S2CNewRoomAddNotify.pb.h" 
#include "protocol/22001_C2STransferAccountsReq.pb.h" 
#include "protocol/22002_S2CTransferAccountsRsp.pb.h" 
#include "protocol/99990_S2CError.pb.h" 
#include "protocol/99991_S2CErrorEx.pb.h" 

#endif 
